# Generated by Django 4.1.3 on 2022-11-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tts.title",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tts.title",
                verbose_name="제목",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="title",
            field=models.CharField(max_length=200, verbose_name="제목"),
        ),
    ]
