# Generated by Django 4.1.3 on 2022-11-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tts", "0002_alter_audio_project_alter_project_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="speed",
            field=models.BooleanField(default=False, verbose_name="재생속도"),
        ),
    ]
